name: TooExpensiveFix
main: com.budderman18.tooexpensivefix.TooExpensiveFix
description: Plugin that removes the "Too Expensive!" during repair and which fixes all item renamings to 1 level

version: @version@
api-version: '1.13'

authors: [BySwiizen, datatags]