name: Feature Request
title: "[FEATURE] "
description: Suggest a new feature for TooExpensiveFix.

body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines
        Please make sure that your feature isn't something already in TooExpensiveFix, and that it hasn't been suggested before.
  - type: textarea
    attributes:
      label: Suggestion
      description: |
        Enter your feature here. Try to be as thorough as possible.
        If you are suggesting something such as an event, please try to leave a link to the Javadoc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: Tell us why you want to see this feature added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: Have anything else to add?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Agreement
      description: Please agree to the following before submitting your feature.
      options:
        - label: I have read the guidelines above and affirm I am following them with this feature.
          required: true