name: Build Gradle


on:
  push:
  pull_request:


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    # https://github.com/actions/checkout
    - name: Check out Git repository
      uses: actions/checkout@v4.1.4

    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2

    # https://github.com/gradle/wrapper-validation-action
    - name: Wrapper validation
      uses: gradle/actions/wrapper-validation@v3.3.2

    # https://github.com/actions/setup-java
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'
        java-package: jdk
        architecture: x64
        cache: gradle

    - name: Configure Git
      run: git config --global user.name "Github Actions" && git config --global user.email "actions@github.com"

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build project
      run: ./gradlew build shadowJar

    # https://github.com/actions/upload-artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: TooExpensiveFix
        path: build/libs/TooExpensiveFix-*.jar