name: Build Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - name: Check out Git repository
      uses: actions/checkout@v3.6.0

    # https://github.com/gradle/wrapper-validation-action
    - name: Wrapper Validation
      uses: gradle/wrapper-validation-action@v2.0.0

    # https://github.com/actions/setup-java
    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build Project
      run: ./gradlew build

    # https://github.com/actions/upload-artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TooExpensiveFix
        path: build/libs/TooExpensiveFix-*.jar