name: Build Gradle


on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    # https://github.com/actions/checkout
    - name: Check out Git repository
      uses: actions/checkout@v4.1.7

    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    # https://github.com/gradle/wrapper-validation-action
    - name: Wrapper validation
      uses: gradle/actions/wrapper-validation@v4.0.0

    # https://github.com/actions/setup-java
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'temurin'
        java-version: '21'
        java-package: jdk
        architecture: x64
        cache: gradle

    - name: Configure Git
      run: git config --global user.name "Github Actions" && git config --global user.email "actions@github.com"

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    # https://github.com/nick-fields/retry
    - name: Build project
      uses: nick-invision/retry@v3.0.0
      with:
        max_attempts: 2
        timeout_minutes: 5
        command: ./gradlew build shadowJar

    # https://github.com/actions/upload-artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: TooExpensiveFix
        path: build/libs/TooExpensiveFix-*.jar