name: Build Gradle


on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - name: Check out Git repository
      uses: actions/checkout@v4.1.2

    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.2.1

    # https://github.com/gradle/wrapper-validation-action
    - name: Wrapper Validation
      uses: gradle/wrapper-validation-action@v3.3.0

    # https://github.com/actions/setup-java
    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: jdk
        architecture: x64
        cache: gradle

    - name: Configure Git
      run: git config --global user.name "Github Actions" && git config --global user.email "actions@github.com"

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build Project
      run: ./gradlew build shadowJar

    # https://github.com/actions/upload-artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: TooExpensiveFix
        path: build/libs/TooExpensiveFix-*.jar