name: Build Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - name: Check out Git repository
      uses: actions/checkout@v3

    # https://github.com/actions/setup-java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Project
      run: mvn -B package --file pom.xml

    # https://github.com/actions/upload-artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: TooExpensiveFix
        path: target/TooExpensiveFix-*.jar