name: TestMC


on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
      # https://github.com/actions/checkout
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      # https://github.com/actions/setup-java
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
          architecture: x64
          cache: gradle

      - name: Configure Git
        run: git config --global user.name "Github Actions" && git config --global user.email "actions@github.com"

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build shadowJar

      # https://github.com/gmitch215/TestMC
      - uses: gmitch215/TestMC@v2.0.0
        with:
          runtime: 'spigot'
          version: '1.21'
          time: 120
          path: 'build/libs/TooExpensiveFix-*.jar'