name: Update Gradle Wrapper


on:
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * 1"


jobs:
  update-gradle-wrapper:

    runs-on: ubuntu-22.04

    steps:
      # https://github.com/actions/checkout
      - name: Check out Git repository
        uses: actions/checkout@v4.2.1

      # https://github.com/gradle/wrapper-validation-action
      - name: Wrapper validation
        uses: gradle/actions/wrapper-validation@v4.1.0

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # https://github.com/gradle-update/update-gradle-wrapper-action
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.0.0
        with:
          release-channel: stable
          labels: dependencies
          reviewers: BySwiizen